export const ROLES = {
  ADMIN: 'admin',
  REVIEWER: 'reviewer',
  CUSTOMER: 'customer',
  STAFF: 'staff',
};

export const CLAIM_STATUS = {
  SUBMITTED: 'submitted',
  UNDER_REVIEW: 'under_review',
  APPROVED: 'approved',
  REJECTED: 'rejected',
  ESCALATED: 'escalated',
  RESOLVED: 'resolved',
  CLOSED: 'closed',
};

export const AI_DECISION = {
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
  ESCALATE: 'ESCALATE',
};

export const WARRANTY_STATUS = {
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  VOIDED: 'VOIDED',
  CLAIMED: 'CLAIMED',
};

export const PRODUCT_CATEGORIES = [
  { id: 'ELECTRONICS', label: 'Consumer Electronics' },
  { id: 'HOME_APPLIANCES', label: 'Home Appliances' },
  { id: 'MOBILE_PHONES', label: 'Mobile Phones & Tablets' },
  { id: 'LAPTOPS', label: 'Laptops & Computers' },
  { id: 'AUDIO', label: 'Audio & Headphones' },
  { id: 'CAMERAS', label: 'Cameras & Photography' },
  { id: 'GAMING', label: 'Gaming & Consoles' },
  { id: 'WEARABLES', label: 'Smartwatches & Wearables' },
  { id: 'NETWORKING', label: 'Networking & Routers' },
  { id: 'PRINTERS', label: 'Printers & Scanners' },
  { id: 'KITCHEN', label: 'Kitchen Appliances' },
  { id: 'POWER_TOOLS', label: 'Power Tools & Equipment' },
];

export const FAULT_TYPES = {
  ELECTRONICS: [
    'Screen Defect / Dead Pixels',
    'Motherboard / Power Supply Failure',
    'Audio / Speaker Malfunction',
    'Port / Connectivity Issue',
    'Software / Firmware Brick',
    'Physical Damage (Accidental)',
    'Water / Liquid Ingress',
    'Other Electrical Failure',
  ],
  HOME_APPLIANCES: [
    'Compressor Failure',
    'Motor / Belt Breakdown',
    'Thermostat / Heating Element Fault',
    'Water Leakage / Plumbing Failure',
    'Control Board Error',
    'Physical Wear & Tear',
    'Noise / Vibration Anomaly',
    'Other Mechanical Failure',
  ],
  MOBILE_PHONES: [
    'Display Shatter / Touch Failure',
    'Battery Degradation / Swelling',
    'Charging Port Malfunction',
    'Camera Sensor Failure',
    'Liquid Damage',
    'Overheating Issue',
    'Network / Modem Failure',
    'Other Component Failure',
  ],
  LAPTOPS: [
    'Screen Crack / Backlight Failure',
    'Keyboard / Touchpad Malfunction',
    'RAM / Storage Drive Failure',
    'Battery Not Charging',
    'CPU / GPU Overheating',
    'Hinge / Chassis Damage',
    'Wi-Fi Card Failure',
    'OS Boot Failure',
  ],
  AUDIO: [
    'No Sound / Distorted Audio',
    'Microphone Failure',
    'Bluetooth Pairing Issue',
    'Charging Case Defect',
    'Driver / Firmware Failure',
    'Physical Damage',
    'Water Ingress',
    'Other Audio Fault',
  ],
  CAMERAS: [
    'Lens Autofocus Failure',
    'Sensor Dead Pixels',
    'Shutter Mechanism Fault',
    'LCD Screen Damage',
    'Battery / Charging Issue',
    'Memory Card Slot Defect',
    'Physical Impact Damage',
    'Firmware Corruption',
  ],
  GAMING: [
    'Disc Drive Failure',
    'Controller Drift / Button Fault',
    'Overheating / Thermal Shutdown',
    'HDMI / Display Port Fault',
    'Storage Corruption',
    'Network / Online Connectivity',
    'Physical Case Damage',
    'Power Supply Failure',
  ],
  WEARABLES: [
    'Screen Crack / Touch Failure',
    'Heart Rate Sensor Fault',
    'GPS Inaccuracy',
    'Battery Life Degradation',
    'Charging Cradle Defect',
    'Water Resistance Failure',
    'Software / OS Crash',
    'Strap / Band Breakage',
  ],
  NETWORKING: [
    'No Internet Connectivity',
    'Wi-Fi Signal Dropout',
    'Port / LAN Failure',
    'Firmware Corruption',
    'Overheating / Shutdown',
    'Power Adapter Failure',
    'Physical Damage',
    'Other Network Fault',
  ],
  PRINTERS: [
    'Paper Jam Mechanism',
    'Print Head Clog / Failure',
    'Ink / Toner Cartridge Issue',
    'Wi-Fi / USB Connectivity',
    'Display / Control Panel Fault',
    'Feed Roller Damage',
    'Scanner Lamp Failure',
    'Driver / Firmware Issue',
  ],
  KITCHEN: [
    'Heating Element Failure',
    'Motor / Blade Breakdown',
    'Electrical Short / Burn',
    'Seal / Gasket Leak',
    'Display / Control Fault',
    'Physical Crack / Damage',
    'Water Pump Failure',
    'Other Mechanical Fault',
  ],
  POWER_TOOLS: [
    'Motor Burnout',
    'Gear / Chuck Failure',
    'Battery Pack Defect',
    'Switch / Trigger Fault',
    'Blade / Bit Defect',
    'Overload Protection Trip',
    'Physical Housing Crack',
    'Cord / Plug Damage',
  ],
};

export const DOCUMENT_TYPES = [
  { id: 'purchase_receipt', label: 'Original Purchase Receipt / Invoice', required: true },
  { id: 'warranty_card', label: 'Warranty Card / Certificate', required: false },
  { id: 'device_photo', label: 'Photo of Defective Device', required: true },
  { id: 'damage_close_up', label: 'Close-Up Photo of Damage / Fault', required: true },
  { id: 'serial_barcode', label: 'Serial Number Barcode / Label', required: false },
  { id: 'repair_estimate', label: 'Authorized Diagnostic / Estimate', required: false },
];

export const AI_COMPARISON_CATEGORIES = {
  STRONG_MATCH: { label: 'Strong Match', color: 'emerald', bg: 'bg-emerald-500/10', text: 'text-emerald-500', border: 'border-emerald-500/30' },
  ACCEPTABLE: { label: 'Acceptable Delta', color: 'blue', bg: 'bg-blue-500/10', text: 'text-blue-500', border: 'border-blue-500/30' },
  WEAK: { label: 'Weak Match', color: 'amber', bg: 'bg-amber-500/10', text: 'text-amber-500', border: 'border-amber-500/30' },
  DISAGREEMENT: { label: 'Model Disagreement', color: 'rose', bg: 'bg-rose-500/10', text: 'text-rose-500', border: 'border-rose-500/30' },
};